/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001.geometry} material={materials.m_eyes} />
      <mesh geometry={nodes.Sphere001_1.geometry} material={materials.m_hair2} />
      <mesh geometry={nodes.Sphere001_2.geometry} material={materials.t_hair} />
      <mesh geometry={nodes.Sphere001_3.geometry} material={materials.m_body} />
      <mesh geometry={nodes.Sphere001_4.geometry} material={materials.m_face} />
    </group>
  )
}

useGLTF.preload('/model.glb')
