/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/Room.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.22, 1.72, -1.39]} rotation={[1.33, -0.26, 1.11]} scale={0.01}>
        <primitive object={nodes.Hips} />
      </group>
      <group position={[-1.31, 2.32, -0.99]} rotation={[1.54, -0.25, 2.34]} scale={-0.01}>
        <primitive object={nodes.Hips_1} />
      </group>
      <mesh geometry={nodes.Plane002.geometry} material={materials.m_stage} />
      <mesh geometry={nodes.Plane002_1.geometry} material={materials.m_PK_black} />
      <mesh geometry={nodes.Plane002_2.geometry} material={materials.m_eyes} />
      <mesh geometry={nodes.Plane002_3.geometry} material={materials.m_hair2} />
      <mesh geometry={nodes.Plane002_4.geometry} material={materials.m_hair} />
      <mesh geometry={nodes.Plane002_5.geometry} material={materials.m_body} />
      <mesh geometry={nodes.Plane002_6.geometry} material={materials.m_face} />
      <mesh geometry={nodes.Plane002_7.geometry} material={materials.m_PK_white} />
      <mesh geometry={nodes.Plane002_8.geometry} material={materials.m_koto} />
      <mesh geometry={nodes.Plane002_9.geometry} material={materials.m_cushion} />
      <mesh geometry={nodes.Plane002_10.geometry} material={materials.m_yane} />
      <mesh geometry={nodes.Plane002_11.geometry} material={materials.m_wood} />
      <mesh geometry={nodes.Plane002_12.geometry} material={materials['m_ plastics']} />
      <mesh geometry={nodes.Plane002_13.geometry} material={materials.m_cloth} />
      <mesh geometry={nodes.Plane002_14.geometry} material={materials.m_gen} />
      <mesh geometry={nodes.Plane002_15.geometry} material={materials.m_zi} />
    </group>
  )
}

useGLTF.preload('/Room.glb')
